---
- hosts: all
  become: true
  tasks:
    #########################################
    # Common packages
    #########################################
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure Python3 pip is installed
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Install Docker Python module via OS package
      apt:
        name: python3-docker
        state: present
        update_cache: yes

#########################################
# Instance C - PostgreSQL
#########################################
- hosts: instance-c
  become: true
  tasks:
    - name: Run PostgreSQL container
      docker_container:
        name: ironhack-project-1_db_1
        image: postgres:15-alpine
        state: started
        restart_policy: always
        env:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "postgres"
        ports:
          - "5432:5432"
        volumes:
          - "/var/lib/postgresql/data/ironhack-db:/var/lib/postgresql/data"
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres"]
          interval: 5s
          retries: 5
          start_period: 10s

#########################################
# Instance B - Redis + Worker
#########################################
- hosts: instance-b
  become: true
  tasks:
    - name: Create Docker network
      docker_network:
        name: ironhack-net
        state: present

    - name: Run Redis container
      docker_container:
        name: ironhack-project-1_redis_1
        image: redis:alpine
        state: started
        restart_policy: always
        ports:
          - "6379:6379"
        networks:
          - name: ironhack-net
        healthcheck:
          test: ["CMD", "redis-cli", "ping"]
          interval: 5s
          retries: 5
          start_period: 5s

    - name: Wait for Redis to be ready
      wait_for:
        host: 127.0.0.1
        port: 6379
        delay: 5
        timeout: 30

    - name: Run Worker container
      docker_container:
        name: ironhack-project-1_worker_1
        image: pokfinner/worker:latest
        state: started
        restart_policy: always
        env:
          DB_HOST: "10.0.2.244"      # Instance C IP
          DB_USERNAME: "postgres"
          DB_PASSWORD: "postgres"
          DB_NAME: "postgres"
          REDIS_HOST: "10.0.2.24"    # Instance B IP
          REDIS_PORT: "6379"
        networks:
          - name: ironhack-net

#########################################
# Instance A - Vote + Result
#########################################
- hosts: instance-a
  become: true
  tasks:
    - name: Wait for PostgreSQL to be ready
      wait_for:
        host: 10.0.2.244
        port: 5432
        delay: 5
        timeout: 60

    - name: Wait for Redis to be ready
      wait_for:
        host: 10.0.2.24
        port: 6379
        delay: 5
        timeout: 30

    - name: Run Vote container
      docker_container:
        name: ironhack-project-1_vote_1
        image: pokfinner/vote:latest
        state: started
        restart_policy: always
        ports:
          - "8080:80"
        env:
          REDIS_HOST: "10.0.2.24"
          REDIS_PORT: "6379"

    - name: Run Result container
      docker_container:
        name: ironhack-project-1_result_1
        image: pokfinner/result:latest
        state: started
        restart_policy: always
        ports:
          - "8081:80"
        env:
          PG_HOST: "10.0.2.244"
          PG_PORT: "5432"
          PG_USER: "postgres"
          PG_PASSWORD: "postgres"